### PR TITLE
fixed main file

### PR DESCRIPTION
**Pull request by donaldpipowitch**
It looks like the wrong file name was used here.

### CODE REVIEW

**Comment by grozen** [comment]
Much obliged.

**Comment by donaldpipowitch** [comment]
Thanks for merging :) Do you already know when you plan to push a new release? :) Thank you.

**Comment by grozen** [comment]
Soon-ish. I've left this to rot for quite a while so I'll take this opportunity to add linting and update some of the dependencies.

**Comment by donaldpipowitch** [comment]
Nice.

**Comment by grozen** [comment]
There we go, just published 1.1.0.

**Pull request merged**
